# Generated by Django 4.2 on 2024-11-06 21:52

from django.db import migrations, models
import stocks_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='INFO', max_length=50)),
                ('request_tmstp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='NA', max_length=16)),
                ('purchased_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('purchased_status', models.CharField(default='NA', max_length=32)),
                ('company_code', models.CharField(default='NA', max_length=32)),
                ('company_name', models.CharField(default='NA', max_length=128)),
                ('stock_values', models.JSONField(default=stocks_api.models.get_stock_values_dict)),
                ('performance_data', models.JSONField(default=stocks_api.models.get_performance_data_dict)),
                ('competitors', models.JSONField(default=stocks_api.models.get_competitors_dict)),
                ('request_data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
