# Generated by Django 4.2 on 2024-11-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='message',
            field=models.CharField(default='NA', max_length=256),
            preserve_default=False,
        ),
    ]
