# Generated by Django 4.2 on 2024-11-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_api', '0002_requestlog_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='level',
            field=models.CharField(default='INFO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='message',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='request_tmstp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
