# Generated by Django 4.2 on 2024-11-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_api', '0003_alter_requestlog_level_alter_requestlog_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
